const express = require('express');
const { Pool } = require('pg');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');

const app = express();

// 🛡️ Seguridad base
// - helmet añade cabeceras seguras por defecto (oculta X-Powered-By, evita
//   sniffing de tipo MIME, fija Content-Security-Policy básica, etc.)
app.disable('x-powered-by');
// La app sirve HTML estático con <script> y <style> inline (sin build
// step ni archivos .js/.css separados), así que el CSP por defecto de
// helmet (que bloquea todo lo inline) rompería el JavaScript de cada
// página. Lo abrimos explícitamente para inline + Google Fonts, y
// dejamos el resto de protecciones de helmet como están.
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      ...helmet.contentSecurityPolicy.getDefaultDirectives(),
      "script-src": ["'self'", "'unsafe-inline'"],
      "script-src-attr": ["'self'", "'unsafe-inline'"],
      "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      "font-src": ["'self'", "https://fonts.gstatic.com", "data:"]
    }
  }
}));

// - límite de peticiones por IP: mitiga fuerza bruta / scraping masivo
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutos
  max: 300,                 // peticiones por IP en esa ventana
  standardHeaders: true,
  legacyHeaders: false
});
app.use('/api/', limiter);

app.use(express.json({ limit: '1mb' })); // límite de tamaño de body, evita payloads gigantes
app.use(express.static('public', {
  dotfiles: 'deny', // nunca sirvas .env, .git, etc.
  index: ['index.html']
}));

// Nota sobre inyección SQL: todas las consultas de este archivo usan
// parámetros ($1, $2...) de node-postgres en vez de concatenar texto, que
// es la defensa real contra SQL injection. Nunca metas variables directamente
// dentro de un template string SQL (`... WHERE x = ${valor}`), siempre $n.

// 🔑 Conexión a PostgreSQL (Render)
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

// Respuesta de error genérica: registra el detalle real en el log del
// servidor (Render lo verás en tus logs), pero nunca lo devuelve tal cual
// al cliente — un mensaje de error de Postgres puede revelar nombres de
// tabla/columna útiles para un atacante.
function errorHandler(res, error, mensajePublico = 'Error del servidor') {
  console.error(error);
  res.status(500).json({ success: false, error: mensajePublico });
}

// 🔥 TEST DB
app.get('/api/test-db', async (req, res) => {
  try {
    const result = await pool.query('SELECT NOW()');
    res.json({
      success: true,
      time: result.rows[0],
    });
  } catch (error) {
    errorHandler(res, error, 'No se pudo conectar a la base de datos');
  }
});

// ⚠️ TEMPORAL: BORRA la tabla castellers ENTERA (todas las columnas y filas)
// y la crea de nuevo con el esquema alineado 1:1 al CSV. Sin ?confirm=si
// solo muestra un aviso; con ?confirm=si sí que la borra y recrea.
// BÓRRALA del código en cuanto la hayas ejecutado una vez.
// ⚠️ TEMPORAL: BORRA por completo los datos de miembros (castellers +
// sus rols de castell asignados) y recrea la tabla con el esquema FINAL
// (con "posicionPinyaId", sin la vieja columna "rol"). Los catálogos
// roles_castillo / posiciones_pinya NO se tocan (se crean/siembran si
// faltan). Sin ?confirm=si solo avisa. BÓRRALA del código en cuanto la
// hayas ejecutado.
app.get('/api/reset-miembros', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto BORRA todos los castellers y sus rols asignados, y recrea la tabla con el esquema final. Añade ?confirm=si para confirmar, ej: /api/reset-miembros?confirm=si'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS posiciones_pinya (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `CREATE TABLE IF NOT EXISTS roles_castillo (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `INSERT INTO posiciones_pinya ("nombre") VALUES
       ('MANS'), ('NOVATOS'), ('CROSSES'), ('LATERALS'), ('CONTRAFORTS'),
       ('BAIXOS'), ('DAUS'), ('GRALLES I TABALS'), ('ALTRES')
     ON CONFLICT ("nombre") DO NOTHING`,
    `INSERT INTO roles_castillo ("nombre") VALUES
       ('Baix'), ('Segon'), ('Terç'), ('Acotxador'), ('Enxaneta')
     ON CONFLICT ("nombre") DO NOTHING`,
    `DROP TABLE IF EXISTS casteller_roles`,
    `DROP TABLE IF EXISTS castellers CASCADE`,
    `CREATE TABLE castellers (
       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       "nombre" TEXT NOT NULL,
       "primerApellido" TEXT,
       "segundoApellido" TEXT,
       "apodo" TEXT,
       "posicionPinyaId" INTEGER REFERENCES posiciones_pinya("id"),
       "accesoAPP" BOOLEAN,
       "correo" TEXT,
       "fNac" DATE,
       "movil" TEXT,
       "fechaCamisa" DATE,
       "alturaHombros" INTEGER,
       "revisado" BOOLEAN,
       "estadoAcogida" TEXT,
       "habitual" BOOLEAN,
       "permisosAPP" TEXT[],
       "integranteColla" BOOLEAN,
       "lesionLargoPlazo" BOOLEAN,
       "formularios" INTEGER,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     )`,
    `CREATE TABLE casteller_roles (
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       "rolId" INTEGER NOT NULL REFERENCES roles_castillo("id") ON DELETE CASCADE,
       "orden" INTEGER NOT NULL,
       PRIMARY KEY ("castellerId", "rolId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  const fallos = resultados.filter(r => !r.ok);
  res.json({
    success: fallos.length === 0,
    detalle: resultados,
    aviso: 'Tabla de miembros recreada. Borra /api/reset-miembros del server.js ahora que ya la has usado. Después de importar el CSV, visita una vez /api/fix-id-sequence.'
  });
});

// ⚠️ TEMPORAL: separa "rol" (texto libre, hoy la Posició del CSV) en dos
// conceptos: catálogo de posicions de pinya (FK, un valor por casteller) y
// catálogo de rols de castell (vector ordenado, varios por casteller, vía
// la taula pont casteller_roles). Migra los datos existentes de "rol" hacia
// "posicionPinyaId" antes de borrar la columna de texto. Sin ?confirm=si
// solo avisa. BÓRRALA del código en cuanto la hayas ejecutado.
app.get('/api/migrate-roles', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea roles_castillo, posiciones_pinya y casteller_roles, migra "rol" a "posicionPinyaId" y borra la columna "rol". Añade ?confirm=si para confirmar.'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS roles_castillo (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `CREATE TABLE IF NOT EXISTS posiciones_pinya (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `INSERT INTO roles_castillo ("nombre") VALUES
       ('Baix'), ('Segon'), ('Terç'), ('Acotxador'), ('Enxaneta')
     ON CONFLICT ("nombre") DO NOTHING`,
    `INSERT INTO posiciones_pinya ("nombre") VALUES
       ('MANS'), ('NOVATOS'), ('CROSSES'), ('LATERALS'), ('CONTRAFORTS'),
       ('BAIXOS'), ('DAUS'), ('GRALLES I TABALS'), ('ALTRES')
     ON CONFLICT ("nombre") DO NOTHING`,
    `ALTER TABLE castellers ADD COLUMN IF NOT EXISTS "posicionPinyaId" INTEGER REFERENCES posiciones_pinya("id")`,
    `UPDATE castellers c
       SET "posicionPinyaId" = pp."id"
       FROM posiciones_pinya pp
       WHERE pp."nombre" = c."rol" AND c."posicionPinyaId" IS NULL`,
    `ALTER TABLE castellers DROP COLUMN IF EXISTS "rol"`,
    `CREATE TABLE IF NOT EXISTS casteller_roles (
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       "rolId" INTEGER NOT NULL REFERENCES roles_castillo("id") ON DELETE CASCADE,
       "orden" INTEGER NOT NULL,
       PRIMARY KEY ("castellerId", "rolId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  const fallos = resultados.filter(r => !r.ok);
  res.json({
    success: fallos.length === 0,
    detalle: resultados,
    aviso: 'Borra /api/migrate-roles del server.js ahora que ya la has ejecutado.'
  });
});

// ⚠️ TEMPORAL: tras importar el CSV (que trae sus propios "id" con huecos,
// del 1 al 1434), la secuencia interna de autoincremento de Postgres no se
// entera de esos valores. Esto la deja apuntando al siguiente número libre,
// para que añadir un casteller nuevo a mano no choque con un id importado.
// BÓRRALA también del código cuando ya no la necesites.
app.get('/api/fix-id-sequence', async (req, res) => {
  try {
    await pool.query(
      `SELECT setval(pg_get_serial_sequence('castellers', 'id'), COALESCE((SELECT MAX("id") FROM castellers), 1))`
    );
    res.json({ success: true, mensaje: 'Seqüència d\'id ajustada correctament.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

// api para cargar miembros y sus datos
app.post('/api/castellers', async (req, res) => {
  try {
    const {
      id, nombre, primerApellido, segundoApellido, apodo, posicionPinyaId,
      accesoAPP, correo, fNac, movil, fechaCamisa, alturaHombros,
      revisado, estadoAcogida, habitual, permisosAPP, integranteColla,
      lesionLargoPlazo, formularios
    } = req.body;

    if (!nombre) {
      return res.status(400).json({ error: 'nombre es obligatorio' });
    }

    const columnas = [
      'nombre', 'primerApellido', 'segundoApellido', 'apodo', 'posicionPinyaId',
      'accesoAPP', 'correo', 'fNac', 'movil', 'fechaCamisa', 'alturaHombros',
      'revisado', 'estadoAcogida', 'habitual', 'permisosAPP', 'integranteColla',
      'lesionLargoPlazo', 'formularios'
    ];
    const valores = [
      nombre,
      primerApellido || null,
      segundoApellido || null,
      apodo || null,
      (posicionPinyaId === '' || posicionPinyaId === undefined) ? null : posicionPinyaId,
      accesoAPP === undefined ? null : accesoAPP,
      correo || null,
      fNac || null,
      movil || null,
      fechaCamisa || null,
      (alturaHombros === '' || alturaHombros === undefined) ? null : alturaHombros,
      revisado === undefined ? null : revisado,
      estadoAcogida || null,
      habitual === undefined ? null : habitual,
      Array.isArray(permisosAPP) ? permisosAPP : (permisosAPP ? [permisosAPP] : null),
      integranteColla === undefined ? null : integranteColla,
      lesionLargoPlazo === undefined ? null : lesionLargoPlazo,
      (formularios === '' || formularios === undefined) ? null : formularios
    ];

    // Si viene un "id" explícito (p. ej. al importar el CSV), lo respetamos.
    // Si no, dejamos que la tabla lo autogenere (alta manual de un casteller).
    if (id !== undefined && id !== null && id !== '') {
      columnas.unshift('id');
      valores.unshift(id);
    }

    const columnasSQL = columnas.map(c => `"${c}"`).join(', ');
    const placeholders = columnas.map((_, i) => `$${i + 1}`).join(', ');

    const result = await pool.query(
      `INSERT INTO castellers (${columnasSQL}) VALUES (${placeholders}) RETURNING *`,
      valores
    );

    res.json({
      success: true,
      casteller: result.rows[0]
    });

  } catch (error) {
    errorHandler(res, error);
  }
});

//api para visualizar miembros (incluye posició pinya i el vector de rols de castell)
app.get('/api/castellers', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT
        c.*,
        pp."nombre" AS "posicionPinyaNombre",
        COALESCE(
          (SELECT json_agg(json_build_object('id', rc."rolId", 'nombre', rcast."nombre", 'orden', rc."orden") ORDER BY rc."orden")
           FROM casteller_roles rc
           JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
           WHERE rc."castellerId" = c."id"),
          '[]'
        ) AS "rolesCastell"
      FROM castellers c
      LEFT JOIN posiciones_pinya pp ON pp."id" = c."posicionPinyaId"
      ORDER BY c."id" DESC
    `);
    res.json({
      success: true,
      data: result.rows
    });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api para el catàleg de posicions de pinya
app.get('/api/posiciones-pinya', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM posiciones_pinya ORDER BY "id"');
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api para el catàleg de rols de castell
app.get('/api/roles-castillo', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM roles_castillo ORDER BY "id"');
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api per llegir el vector de rols (ordenat) d'un casteller concret
app.get('/api/castellers/:id/roles', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `SELECT rc."rolId" AS "id", rcast."nombre", rc."orden"
       FROM casteller_roles rc
       JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
       WHERE rc."castellerId" = $1
       ORDER BY rc."orden"`,
      [id]
    );
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api per desar el vector de rols (ordenat, el primer és el principal) d'un casteller
app.put('/api/castellers/:id/roles', async (req, res) => {
  const { id } = req.params;
  const { rolIds } = req.body; // array ordenat d'ids de roles_castillo

  if (!Array.isArray(rolIds)) {
    return res.status(400).json({ error: 'rolIds ha de ser un array d\'ids, en ordre (principal primer)' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('DELETE FROM casteller_roles WHERE "castellerId" = $1', [id]);

    for (let i = 0; i < rolIds.length; i++) {
      await client.query(
        `INSERT INTO casteller_roles ("castellerId", "rolId", "orden") VALUES ($1, $2, $3)`,
        [id, rolIds[i], i + 1]
      );
    }

    await client.query('COMMIT');
    res.json({ success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

//api para editar un miembro existente
app.put('/api/castellers/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const {
      nombre, primerApellido, segundoApellido, apodo, posicionPinyaId,
      accesoAPP, correo, fNac, movil, fechaCamisa, alturaHombros,
      revisado, estadoAcogida, habitual, permisosAPP, integranteColla,
      lesionLargoPlazo, formularios
    } = req.body;

    if (!nombre) {
      return res.status(400).json({ error: 'nombre es obligatorio' });
    }

    const result = await pool.query(
      `UPDATE castellers SET
         "nombre" = $1, "primerApellido" = $2, "segundoApellido" = $3, "apodo" = $4, "posicionPinyaId" = $5,
         "accesoAPP" = $6, "correo" = $7, "fNac" = $8, "movil" = $9, "fechaCamisa" = $10,
         "alturaHombros" = $11, "revisado" = $12, "estadoAcogida" = $13, "habitual" = $14,
         "permisosAPP" = $15, "integranteColla" = $16, "lesionLargoPlazo" = $17, "formularios" = $18
       WHERE "id" = $19
       RETURNING *`,
      [
        nombre,
        primerApellido || null,
        segundoApellido || null,
        apodo || null,
        (posicionPinyaId === '' || posicionPinyaId === undefined) ? null : posicionPinyaId,
        accesoAPP === undefined ? null : accesoAPP,
        correo || null,
        fNac || null,
        movil || null,
        fechaCamisa || null,
        (alturaHombros === '' || alturaHombros === undefined) ? null : alturaHombros,
        revisado === undefined ? null : revisado,
        estadoAcogida || null,
        habitual === undefined ? null : habitual,
        Array.isArray(permisosAPP) ? permisosAPP : (permisosAPP ? [permisosAPP] : null),
        integranteColla === undefined ? null : integranteColla,
        lesionLargoPlazo === undefined ? null : lesionLargoPlazo,
        (formularios === '' || formularios === undefined) ? null : formularios,
        id
      ]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Casteller no trobat' });
    }

    res.json({
      success: true,
      casteller: result.rows[0]
    });

  } catch (error) {
    errorHandler(res, error);
  }
});

//api generar castells
// Cada casteller ahora puede tener VARIOS rols de castell asignados
// (baix/segon/terç/acotxador/enxaneta), guardados en casteller_roles con un
// orden (1 = principal). Para generar propuestas, contamos a alguien como
// elegible para un rol si ese rol está en su vector, sin importar el orden
// — es una asunción de partida (cualquier rol asignado cuenta igual), no
// distingue todavía "rol principal" de "también sabe hacerlo".
app.get('/api/generar', async (req, res) => {
  try {
    const resultado = await pool.query(`
      SELECT
        c."id", c."nombre", c."alturaHombros",
        COALESCE(
          array_agg(lower(rcast."nombre")) FILTER (WHERE rcast."nombre" IS NOT NULL),
          '{}'
        ) AS roles
      FROM castellers c
      LEFT JOIN casteller_roles rc ON rc."castellerId" = c."id"
      LEFT JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
      GROUP BY c."id"
    `);
    const castellers = resultado.rows;

    const obtenerMasAltos = (arr) => [...arr].sort((a, b) => b.alturaHombros - a.alturaHombros);
    const obtenerMasBajos = (arr) => [...arr].sort((a, b) => a.alturaHombros - b.alturaHombros);

    const estructuras = [
      { nombre: '2d6', segons: 2, tersos: 2 },
      { nombre: '3d7', segons: 3, tersos: 3 },
      { nombre: '4d7', segons: 4, tersos: 4 },
      { nombre: '5d7', segons: 5, tersos: 5 }
    ];

    const calcularRiesgo = ({ baix, segons, tersos, pom }) => {
      let riesgo = 0;

      const mediaSegons = segons.reduce((acc, s) => acc + s.alturaHombros, 0) / segons.length;
      const mediaTersos = tersos.reduce((acc, t) => acc + t.alturaHombros, 0) / tersos.length;

      riesgo += Math.abs(baix.alturaHombros - mediaSegons) * 0.3;
      riesgo += Math.abs(mediaSegons - mediaTersos) * 0.3;

      if (pom.enxaneta.alturaHombros > 140) riesgo += 20;
      if (pom.acotxador.alturaHombros > 150) riesgo += 15;

      return Math.round(riesgo);
    };

    const clasificarRiesgo = (riesgo) => {
      if (riesgo < 20) return '🟢 Seguro';
      if (riesgo < 50) return '🟡 Medio';
      return '🔴 Alto';
    };

    const generarParaEstructura = (config) => {

      const baixos = castellers.filter(c => c.roles.includes('baix'));
      const segons = castellers.filter(c => c.roles.includes('segon'));
      const tersos = castellers.filter(c => c.roles.includes('terç'));
      const acotxadors = castellers.filter(c => c.roles.includes('acotxador'));
      const enxanetes = castellers.filter(c => c.roles.includes('enxaneta'));

      const resultado = {
        tipo: config.nombre,
        valido: true,
        mensajes: []
      };

      if (baixos.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta baix');
      }

      if (segons.length < config.segons) {
        resultado.valido = false;
        resultado.mensajes.push(`Faltan segons (${config.segons})`);
      }

      if (tersos.length < config.tersos) {
        resultado.valido = false;
        resultado.mensajes.push(`Faltan tersos (${config.tersos})`);
      }

      if (acotxadors.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta acotxador');
      }

      if (enxanetes.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta enxaneta');
      }

      if (!resultado.valido) return resultado;

      const estructura = {
        baix: obtenerMasAltos(baixos)[0],
        segons: obtenerMasAltos(segons).slice(0, config.segons),
        tersos: obtenerMasAltos(tersos).slice(0, config.tersos),
        pom: {
          acotxador: obtenerMasBajos(acotxadors)[0],
          enxaneta: obtenerMasBajos(enxanetes)[0]
        }
      };

      const riesgo = calcularRiesgo(estructura);
      const nivel = clasificarRiesgo(riesgo);

      resultado.estructura = estructura;
      resultado.riesgo = riesgo;
      resultado.nivel = nivel;

      return resultado;
    };

    const propuestas = estructuras.map(config => generarParaEstructura(config));

    res.json({
      success: true,
      propuestas
    });

  } catch (error) {
    console.error(error);
    res.status(500).send('Error generando castells');
  }
});

/* =========================================================
   MÒDUL ENSAJOS
   ========================================================= */

// ⚠️ TEMPORAL: crea les taules d'ensayos i assistència. Sense ?confirm=si
// només avisa. BÓRRALA del server.js en cuanto la hayas ejecutado.
app.get('/api/migrate-ensayos', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea las tablas ensayos y ensayo_asistentes. Añade ?confirm=si para confirmar.'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS ensayos (
       "id" SERIAL PRIMARY KEY,
       "fecha" DATE NOT NULL,
       "horaInicio" TIME,
       "horaFin" TIME,
       "notas" TEXT,
       "publicado" BOOLEAN NOT NULL DEFAULT FALSE,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     )`,
    `CREATE TABLE IF NOT EXISTS ensayo_asistentes (
       "ensayoId" INTEGER NOT NULL REFERENCES ensayos("id") ON DELETE CASCADE,
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       PRIMARY KEY ("ensayoId", "castellerId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  res.json({
    success: resultados.every(r => r.ok),
    detalle: resultados,
    aviso: 'Borra /api/migrate-ensayos del server.js ahora que ya la has ejecutado.'
  });
});

// ⚠️ TEMPORAL: crea las tablas de estructuras guardadas por assaig
// (el castell/pinya que se decide conservar) y sus posiciones. Sin
// ?confirm=si solo avisa. BÓRRALA del server.js en cuanto la hayas ejecutado.
app.get('/api/migrate-estructuras', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea las tablas estructuras_ensayo y estructura_posiciones. Añade ?confirm=si para confirmar.'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS estructuras_ensayo (
       "id" SERIAL PRIMARY KEY,
       "ensayoId" INTEGER NOT NULL REFERENCES ensayos("id") ON DELETE CASCADE,
       "tipo" TEXT NOT NULL,
       "notas" TEXT,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     )`,
    // "slot" = nombre de la posición (Baix, Crossa, Soca, Rengle...) tal
    // como aparece en las plantillas; "slotIndex" distingue repeticiones
    // (Crossa-1, Crossa-2...). castellerId nulo = posición vacía todavía.
    `CREATE TABLE IF NOT EXISTS estructura_posiciones (
       "id" SERIAL PRIMARY KEY,
       "estructuraEnsayoId" INTEGER NOT NULL REFERENCES estructuras_ensayo("id") ON DELETE CASCADE,
       "slot" TEXT NOT NULL,
       "slotIndex" INTEGER NOT NULL DEFAULT 1,
       "castellerId" INTEGER REFERENCES castellers("id") ON DELETE SET NULL,
       UNIQUE ("estructuraEnsayoId", "slot", "slotIndex")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  res.json({
    success: resultados.every(r => r.ok),
    detalle: resultados,
    aviso: 'Borra /api/migrate-estructuras del server.js ahora que ya la has ejecutado.'
  });
});

// Crear una estructura guardada dentro de un assaig (p.ex. al pulsar
// "Desar aquesta proposta" en el modal de propostes de castells)
app.post('/api/ensayos/:id/estructuras', async (req, res) => {
  const client = await pool.connect();
  try {
    const { id } = req.params;
    const { tipo, notas } = req.body;
    if (!tipo) return res.status(400).json({ error: 'tipo es obligatorio' });

    // Niveles reals definits a l'editor de castells per a aquest tipus.
    // L'ordre de la llista importa: el PRIMER nivell rep els membres més
    // baixos (ex. Enxaneta), l'ÚLTIM els més alts (ex. Baix) — es pot
    // reordenar arrossegant a l'editor de castells.
    const estructuraDefResult = await client.query(
      `SELECT "niveles" FROM castells_estructura WHERE "tipo" = $1`,
      [tipo]
    );
    const nivelesDefinidos = estructuraDefResult.rows[0] ? estructuraDefResult.rows[0].niveles : null;

    // Si encara no hi ha una estructura de castell definida per a aquest
    // tipus, fem servir uns nivells per defecte (compatibilitat amb el
    // comportament anterior).
    const configsPerDefecte = {
      '2d6': [{ nombre: 'Enxaneta', cantidad: 1 }, { nombre: 'Acotxador', cantidad: 1 }, { nombre: 'Terç', cantidad: 2 }, { nombre: 'Segon', cantidad: 2 }, { nombre: 'Baix', cantidad: 2 }],
      '3d7': [{ nombre: 'Enxaneta', cantidad: 1 }, { nombre: 'Acotxador', cantidad: 1 }, { nombre: 'Terç', cantidad: 3 }, { nombre: 'Segon', cantidad: 3 }, { nombre: 'Baix', cantidad: 3 }],
      '4d7': [{ nombre: 'Enxaneta', cantidad: 1 }, { nombre: 'Acotxador', cantidad: 1 }, { nombre: 'Terç', cantidad: 4 }, { nombre: 'Segon', cantidad: 4 }, { nombre: 'Baix', cantidad: 4 }],
      '5d7': [{ nombre: 'Enxaneta', cantidad: 1 }, { nombre: 'Acotxador', cantidad: 1 }, { nombre: 'Terç', cantidad: 5 }, { nombre: 'Segon', cantidad: 5 }, { nombre: 'Baix', cantidad: 5 }]
    };
    const niveles = nivelesDefinidos || configsPerDefecte[tipo] || configsPerDefecte['3d7'];

    await client.query('BEGIN');

    const estructuraResult = await client.query(
      `INSERT INTO estructuras_ensayo ("ensayoId", "tipo", "notas") VALUES ($1, $2, $3) RETURNING *`,
      [id, tipo, notas || null]
    );
    const estructura = estructuraResult.rows[0];

    // Presents ordenats de més baix a més alt: el primer nivell de la
    // llista (normalment Enxaneta) es queda amb els primers (més baixos).
    const presentesResult = await client.query(
      `SELECT c."id", c."alturaHombros"
       FROM ensayo_asistentes ea
       JOIN castellers c ON c."id" = ea."castellerId"
       WHERE ea."ensayoId" = $1
       ORDER BY c."alturaHombros" ASC NULLS FIRST`,
      [id]
    );
    const presentes = presentesResult.rows;
    const necesarios = niveles.reduce((acc, n) => acc + n.cantidad, 0);

    if (presentes.length >= necesarios) {
      let i = 0;
      const posiciones = [];
      niveles.forEach(nivel => {
        for (let k = 0; k < nivel.cantidad; k++) {
          posiciones.push({ slot: nivel.nombre, slotIndex: k + 1, castellerId: presentes[i++].id });
        }
      });

      for (const p of posiciones) {
        await client.query(
          `INSERT INTO estructura_posiciones ("estructuraEnsayoId", "slot", "slotIndex", "castellerId")
           VALUES ($1, $2, $3, $4)
           ON CONFLICT ("estructuraEnsayoId", "slot", "slotIndex") DO UPDATE SET "castellerId" = EXCLUDED."castellerId"`,
          [estructura.id, p.slot, p.slotIndex, p.castellerId]
        );
      }
    }

    await client.query('COMMIT');
    res.json({ success: true, estructura });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

// Listar las estructuras guardadas de un assaig, con cuántas posiciones
// tienen ya asignadas
app.get('/api/ensayos/:id/estructuras', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(`
      SELECT ee.*,
        COUNT(ep."id")::int AS "totalPosiciones",
        COUNT(ep."castellerId")::int AS "posicionesAsignadas"
      FROM estructuras_ensayo ee
      LEFT JOIN estructura_posiciones ep ON ep."estructuraEnsayoId" = ee."id"
      WHERE ee."ensayoId" = $1
      GROUP BY ee."id"
      ORDER BY ee."created_at" ASC
    `, [id]);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Detalle de una estructura guardada: cabecera + todas sus posiciones
// (con el nombre del casteller asignado, si lo hay)
app.get('/api/estructuras/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const estructura = await pool.query('SELECT * FROM estructuras_ensayo WHERE "id" = $1', [id]);
    if (estructura.rows.length === 0) return res.status(404).json({ error: 'Estructura no trobada' });

    const posiciones = await pool.query(`
      SELECT ep."slot", ep."slotIndex", ep."castellerId", c."nombre" AS "castellerNombre"
      FROM estructura_posiciones ep
      LEFT JOIN castellers c ON c."id" = ep."castellerId"
      WHERE ep."estructuraEnsayoId" = $1
      ORDER BY ep."slot", ep."slotIndex"
    `, [id]);

    res.json({ success: true, estructura: estructura.rows[0], posiciones: posiciones.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Asignar (o vaciar, con castellerId null) un casteller a una posición
// concreta. Sirve tanto para el "arrastrar y soltar" como para colocar
// manualmente en una pinya en blanco.
app.put('/api/estructuras/:id/posiciones', async (req, res) => {
  try {
    const { id } = req.params;
    const { slot, slotIndex, castellerId } = req.body;
    if (!slot) return res.status(400).json({ error: 'slot es obligatorio' });

    const result = await pool.query(
      `INSERT INTO estructura_posiciones ("estructuraEnsayoId", "slot", "slotIndex", "castellerId")
       VALUES ($1, $2, $3, $4)
       ON CONFLICT ("estructuraEnsayoId", "slot", "slotIndex")
       DO UPDATE SET "castellerId" = EXCLUDED."castellerId"
       RETURNING *`,
      [id, slot, slotIndex || 1, castellerId || null]
    );
    res.json({ success: true, posicion: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Intercambiar quién ocupa dos posiciones (drag&drop de sujeto sobre
// sujeto, o el "clic en B, clic en A" que también queréis soportar).
// Crea las filas si alguna posición todavía no existía (pinya en blanco).
app.put('/api/estructuras/:id/swap', async (req, res) => {
  const { id } = req.params;
  const { a, b } = req.body; // { slot, slotIndex } cada una
  if (!a || !b || !a.slot || !b.slot) {
    return res.status(400).json({ error: 'a y b (con slot) son obligatorios' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const upsertVacio = async (pos) => {
      await client.query(
        `INSERT INTO estructura_posiciones ("estructuraEnsayoId", "slot", "slotIndex")
         VALUES ($1, $2, $3)
         ON CONFLICT ("estructuraEnsayoId", "slot", "slotIndex") DO NOTHING`,
        [id, pos.slot, pos.slotIndex || 1]
      );
      const r = await client.query(
        `SELECT "castellerId" FROM estructura_posiciones
         WHERE "estructuraEnsayoId" = $1 AND "slot" = $2 AND "slotIndex" = $3`,
        [id, pos.slot, pos.slotIndex || 1]
      );
      return r.rows[0].castellerId;
    };

    const castellerA = await upsertVacio(a);
    const castellerB = await upsertVacio(b);

    await client.query(
      `UPDATE estructura_posiciones SET "castellerId" = $1
       WHERE "estructuraEnsayoId" = $2 AND "slot" = $3 AND "slotIndex" = $4`,
      [castellerB, id, a.slot, a.slotIndex || 1]
    );
    await client.query(
      `UPDATE estructura_posiciones SET "castellerId" = $1
       WHERE "estructuraEnsayoId" = $2 AND "slot" = $3 AND "slotIndex" = $4`,
      [castellerA, id, b.slot, b.slotIndex || 1]
    );

    await client.query('COMMIT');
    res.json({ success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

// Descartar una estructura guardada (p.ex. una prova que no ha quedat bé)
app.delete('/api/estructuras/:id', async (req, res) => {
  try {
    const { id } = req.params;
    await pool.query('DELETE FROM estructuras_ensayo WHERE "id" = $1', [id]);
    res.json({ success: true });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Llistar tots els ensayos (esborranys inclosos — encara no hi ha usuaris
// per restringir la visibilitat dels privats; això arribarà amb el login)
app.get('/api/ensayos', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT e.*, COUNT(ea."castellerId")::int AS "numAsistentes"
      FROM ensayos e
      LEFT JOIN ensayo_asistentes ea ON ea."ensayoId" = e."id"
      GROUP BY e."id"
      ORDER BY e."fecha" DESC, e."id" DESC
    `);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Crear un ensayo nou
app.post('/api/ensayos', async (req, res) => {
  try {
    const { fecha, horaInicio, horaFin, notas } = req.body;
    if (!fecha) return res.status(400).json({ error: 'fecha es obligatoria' });

    const result = await pool.query(
      `INSERT INTO ensayos ("fecha", "horaInicio", "horaFin", "notas")
       VALUES ($1, $2, $3, $4) RETURNING *`,
      [fecha, horaInicio || null, horaFin || null, notas || null]
    );
    res.json({ success: true, ensayo: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Detall d'un ensayo + llista d'ids de castellers presents
app.get('/api/ensayos/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const ensayo = await pool.query('SELECT * FROM ensayos WHERE "id" = $1', [id]);
    if (ensayo.rows.length === 0) return res.status(404).json({ error: 'Ensayo no trobat' });

    const asistentes = await pool.query(
      'SELECT "castellerId" FROM ensayo_asistentes WHERE "ensayoId" = $1',
      [id]
    );
    res.json({
      success: true,
      ensayo: ensayo.rows[0],
      asistentesIds: asistentes.rows.map(r => r.castellerId)
    });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Marcar/desmarcar l'assistència d'un casteller a un ensayo
app.put('/api/ensayos/:id/asistencia', async (req, res) => {
  try {
    const { id } = req.params;
    const { castellerId, asiste } = req.body;
    if (!castellerId) return res.status(400).json({ error: 'castellerId es obligatorio' });

    if (asiste) {
      await pool.query(
        `INSERT INTO ensayo_asistentes ("ensayoId", "castellerId") VALUES ($1, $2)
         ON CONFLICT DO NOTHING`,
        [id, castellerId]
      );
    } else {
      await pool.query(
        `DELETE FROM ensayo_asistentes WHERE "ensayoId" = $1 AND "castellerId" = $2`,
        [id, castellerId]
      );
    }
    res.json({ success: true });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Publicar un ensayo (deixa de ser esborrany privat)
app.put('/api/ensayos/:id/publicar', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `UPDATE ensayos SET "publicado" = TRUE WHERE "id" = $1 RETURNING *`,
      [id]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Ensayo no trobat' });
    res.json({ success: true, ensayo: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Propostes de castells PER A UN ENSAYO CONCRET, basades només en els
// presents (encara no tenim rols de castell assignats de forma fiable a
// totes les collas que faran servir això, així que aquí NO exigim rols:
// només comptem caps i, opcionalment, ordenem per alçada).
// ?criterio=altura -> suggereix qui podria anar de pom (més baixos) i de
// base (més alts). ?criterio=ninguno (o sense el paràmetre) -> només
// comprova viabilitat per nombre de gent.
app.get('/api/ensayos/:id/propuestas', async (req, res) => {
  try {
    const { id } = req.params;
    const criterio = req.query.criterio === 'altura' ? 'altura' : 'ninguno';

    const result = await pool.query(
      `SELECT c."id", c."nombre", c."alturaHombros"
       FROM ensayo_asistentes ea
       JOIN castellers c ON c."id" = ea."castellerId"
       WHERE ea."ensayoId" = $1`,
      [id]
    );
    const presentes = result.rows;

    // Estructures simplificades: nombre mínim de persones al tronc + pom
    // (1 baix + segons + tersos + acotxador + enxaneta). No modelem encara
    // la pinya de suport.
    const estructuras = [
      { tipo: '2d6', segons: 2, tersos: 2 },
      { tipo: '3d7', segons: 3, tersos: 3 },
      { tipo: '4d7', segons: 4, tersos: 4 },
      { tipo: '5d7', segons: 5, tersos: 5 }
    ];

    const propuestas = estructuras.map(e => {
      const requerido = 1 + e.segons + e.tersos + 1 + 1; // baix + segons + tersos + acotxador + enxaneta
      const viable = presentes.length >= requerido;

      const propuesta = { tipo: e.tipo, requerido, presentes: presentes.length, viable };

      if (viable && criterio === 'altura') {
        const conAltura = presentes.filter(p => p.alturaHombros !== null && p.alturaHombros !== undefined);
        const ordenados = [...conAltura].sort((a, b) => a.alturaHombros - b.alturaHombros);
        propuesta.sugerencia = {
          pom_mas_bajos: ordenados.slice(0, 2).map(p => ({ id: p.id, nombre: p.nombre, alturaHombros: p.alturaHombros })),
          base_mas_altos: ordenados.slice(-2).reverse().map(p => ({ id: p.id, nombre: p.nombre, alturaHombros: p.alturaHombros })),
          sinAlturaRegistrada: presentes.length - conAltura.length
        };
      }

      return propuesta;
    });

    res.json({ success: true, criterio, propuestas });
  } catch (error) {
    errorHandler(res, error);
  }
});

/* =========================================================
   MÒDUL PLANTILLES DE PINYA (editables des de l'editor visual)
   ========================================================= */

// ⚠️ TEMPORAL: crea la taula de plantilles. Sense ?confirm=si només avisa.
// BÓRRALA del server.js en cuanto la hayas ejecutado.
// ⚠️ TEMPORAL: solo para depurar — muestra las columnas reales que Postgres
// tiene guardadas para plantillas_posicion, directamente desde el catálogo
// del sistema (sin pasar por SELECT * ni por ninguna suposición del código).
// Bórrala del server.js en cuanto hayamos resuelto esto.
app.get('/api/debug-columnas', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT column_name, data_type, column_default, is_nullable
      FROM information_schema.columns
      WHERE table_name = 'plantillas_posicion'
      ORDER BY ordinal_position
    `);
    res.json({ success: true, columnas: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.get('/api/migrate-plantillas', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea la tabla plantillas_posicion. Añade ?confirm=si para confirmar.'
    });
  }
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS plantillas_posicion (
        "id" SERIAL PRIMARY KEY,
        "tipo" TEXT NOT NULL,
        "slot" TEXT NOT NULL,
        "slotIndex" INTEGER NOT NULL DEFAULT 1,
        "x" NUMERIC NOT NULL,
        "y" NUMERIC NOT NULL,
        "w" NUMERIC NOT NULL DEFAULT 70,
        "h" NUMERIC NOT NULL DEFAULT 32,
        "shape" TEXT NOT NULL DEFAULT 'rect',
        UNIQUE ("tipo", "slot", "slotIndex")
      )
    `);
    // idempotent: si la tabla ya existía de antes, añade la columna nueva
    await pool.query(`ALTER TABLE plantillas_posicion ADD COLUMN IF NOT EXISTS "rotacion" NUMERIC NOT NULL DEFAULT 0`);
    res.json({ success: true, aviso: 'Borra /api/migrate-plantillas del server.js ahora que ya la has ejecutado.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Llegir la plantilla desada d'un tipus de castell
app.get('/api/plantillas/:tipo', async (req, res) => {
  try {
    const { tipo } = req.params;
    const result = await pool.query('SELECT * FROM plantillas_posicion WHERE "tipo" = $1 ORDER BY "id"', [tipo]);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Desar (reemplaçant) tota la plantilla d'un tipus, tal com l'ha deixat
// l'editor visual
app.put('/api/plantillas/:tipo', async (req, res) => {
  const { tipo } = req.params;
  const { posiciones } = req.body; // array de { slot, slotIndex, x, y, w, h, shape }
  if (!Array.isArray(posiciones)) {
    return res.status(400).json({ error: 'posiciones ha de ser un array' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('DELETE FROM plantillas_posicion WHERE "tipo" = $1', [tipo]);
    for (const p of posiciones) {
      await client.query(
        `INSERT INTO plantillas_posicion ("tipo", "slot", "slotIndex", "x", "y", "w", "h", "shape", "rotacion")
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
        [tipo, p.slot, p.slotIndex || 1, p.x, p.y, p.w || 70, p.h || 32, p.shape || 'rect', p.rotacion || 0]
      );
    }
    await client.query('COMMIT');
    res.json({ success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});


/* =========================================================
   MÒDUL IMATGES DE REFERÈNCIA (biblioteca compartida pels editors)
   ========================================================= */

// ⚠️ TEMPORAL: crea la taula d'imatges. Sense ?confirm=si només avisa.
app.get('/api/migrate-imagenes', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({ success: false, aviso: 'Esto crea la tabla imagenes_referencia. Añade ?confirm=si para confirmar.' });
  }
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS imagenes_referencia (
        "id" SERIAL PRIMARY KEY,
        "nombre" TEXT,
        "categoria" TEXT,
        "dataUrl" TEXT NOT NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    res.json({ success: true, aviso: 'Borra /api/migrate-imagenes del server.js ahora que ya la has ejecutado.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Nota: guardem la imatge com a text (base64 o URL externa) directament a
// Postgres. És senzill i persisteix bé entre desplegaments (el disc local de
// Render s'esborra a cada deploy), però per a una biblioteca molt gran
// d'imatges pesades caldria un servei d'emmagatzematge real més endavant.
app.get('/api/imagenes', async (req, res) => {
  try {
    const { categoria } = req.query;
    const result = categoria
      ? await pool.query('SELECT * FROM imagenes_referencia WHERE "categoria" = $1 ORDER BY "id" DESC', [categoria])
      : await pool.query('SELECT * FROM imagenes_referencia ORDER BY "id" DESC');
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.post('/api/imagenes', async (req, res) => {
  try {
    const { nombre, categoria, dataUrl } = req.body;
    if (!dataUrl) return res.status(400).json({ error: 'dataUrl es obligatorio' });
    const result = await pool.query(
      `INSERT INTO imagenes_referencia ("nombre","categoria","dataUrl") VALUES ($1,$2,$3) RETURNING "id","nombre","categoria","created_at"`,
      [nombre || null, categoria || null, dataUrl]
    );
    res.json({ success: true, imagen: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.delete('/api/imagenes/:id', async (req, res) => {
  try {
    await pool.query('DELETE FROM imagenes_referencia WHERE "id" = $1', [req.params.id]);
    res.json({ success: true });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Renombrar una imatge
app.put('/api/imagenes/:id', async (req, res) => {
  try {
    const { nombre } = req.body;
    if (!nombre) return res.status(400).json({ error: 'nombre es obligatorio' });
    const result = await pool.query(
      `UPDATE imagenes_referencia SET "nombre" = $1 WHERE "id" = $2 RETURNING "id","nombre","categoria","created_at"`,
      [nombre, req.params.id]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Imatge no trobada' });
    res.json({ success: true, imagen: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

/* =========================================================
   MÒDUL CATEGORIES D'IMATGE (gestionables des de la biblioteca)
   ========================================================= */

// ⚠️ TEMPORAL: crea la taula de categories, la sembra amb les 4 inicials, i
// normalitza els valors antics ('pinya'/'castell') cap als noms nous. Sense
// ?confirm=si només avisa.
app.get('/api/migrate-categorias-imagen', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({ success: false, aviso: 'Esto crea categorias_imagen y normaliza categorías antiguas. Añade ?confirm=si para confirmar.' });
  }
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS categorias_imagen (
        "id" SERIAL PRIMARY KEY,
        "nombre" TEXT UNIQUE NOT NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await pool.query(`
      INSERT INTO categorias_imagen ("nombre") VALUES
        ('Castells'), ('Pinyes'), ('Fotos de perfil'), ('Altres')
      ON CONFLICT ("nombre") DO NOTHING
    `);
    // les imatges que es van guardar abans amb categoria='castell'/'pinya'
    // (text lliure en minúscules) passen a fer servir els noms nous
    await pool.query(`UPDATE imagenes_referencia SET "categoria" = 'Castells' WHERE "categoria" = 'castell'`);
    await pool.query(`UPDATE imagenes_referencia SET "categoria" = 'Pinyes' WHERE "categoria" = 'pinya'`);
    await pool.query(`UPDATE imagenes_referencia SET "categoria" = 'Altres' WHERE "categoria" IS NULL OR "categoria" = ''`);
    res.json({ success: true, aviso: 'Borra /api/migrate-categorias-imagen del server.js ahora que ya la has ejecutado.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.get('/api/categorias-imagen', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT c.*, COUNT(i."id")::int AS "numImagenes"
      FROM categorias_imagen c
      LEFT JOIN imagenes_referencia i ON i."categoria" = c."nombre"
      GROUP BY c."id"
      ORDER BY c."nombre"
    `);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.post('/api/categorias-imagen', async (req, res) => {
  try {
    const { nombre } = req.body;
    if (!nombre || !nombre.trim()) return res.status(400).json({ error: 'nombre es obligatorio' });
    const result = await pool.query(
      `INSERT INTO categorias_imagen ("nombre") VALUES ($1) RETURNING *`,
      [nombre.trim()]
    );
    res.json({ success: true, categoria: result.rows[0] });
  } catch (error) {
    if (error.code === '23505') return res.status(400).json({ success: false, error: 'Ja existeix una categoria amb aquest nom' });
    errorHandler(res, error);
  }
});

// Renombrar una categoria — actualitza també totes les imatges que la feien
// servir, perquè quedin sincronitzades amb el nou nom.
app.put('/api/categorias-imagen/:id', async (req, res) => {
  const client = await pool.connect();
  try {
    const { nombre } = req.body;
    if (!nombre || !nombre.trim()) return res.status(400).json({ error: 'nombre es obligatorio' });

    await client.query('BEGIN');
    const actual = await client.query('SELECT * FROM categorias_imagen WHERE "id" = $1', [req.params.id]);
    if (actual.rows.length === 0) {
      await client.query('ROLLBACK');
      return res.status(404).json({ error: 'Categoria no trobada' });
    }
    const nombreAnterior = actual.rows[0].nombre;

    const result = await client.query(
      `UPDATE categorias_imagen SET "nombre" = $1 WHERE "id" = $2 RETURNING *`,
      [nombre.trim(), req.params.id]
    );
    await client.query(
      `UPDATE imagenes_referencia SET "categoria" = $1 WHERE "categoria" = $2`,
      [nombre.trim(), nombreAnterior]
    );
    await client.query('COMMIT');
    res.json({ success: true, categoria: result.rows[0] });
  } catch (error) {
    await client.query('ROLLBACK');
    if (error.code === '23505') return res.status(400).json({ success: false, error: 'Ja existeix una categoria amb aquest nom' });
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

/* =========================================================
   MÒDUL ESTRUCTURA DE CASTELLS (el tronc: nivells i quantitats)
   ========================================================= */

// ⚠️ TEMPORAL: crea la taula d'estructures de castell. Sense ?confirm=si
// només avisa.
app.get('/api/migrate-castells-estructura', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({ success: false, aviso: 'Esto crea la tabla castells_estructura. Añade ?confirm=si para confirmar.' });
  }
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS castells_estructura (
        "id" SERIAL PRIMARY KEY,
        "tipo" TEXT UNIQUE NOT NULL,
        "niveles" JSONB NOT NULL,
        "imagenId" INTEGER REFERENCES imagenes_referencia("id") ON DELETE SET NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    res.json({ success: true, aviso: 'Borra /api/migrate-castells-estructura del server.js ahora que ya la has ejecutado.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.get('/api/castells-estructura/:tipo', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM castells_estructura WHERE "tipo" = $1', [req.params.tipo]);
    if (result.rows.length === 0) return res.json({ success: true, estructura: null });
    res.json({ success: true, estructura: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.put('/api/castells-estructura/:tipo', async (req, res) => {
  try {
    const { tipo } = req.params;
    const { niveles, imagenId } = req.body;
    if (!Array.isArray(niveles)) return res.status(400).json({ error: 'niveles ha de ser un array' });

    const result = await pool.query(
      `INSERT INTO castells_estructura ("tipo","niveles","imagenId")
       VALUES ($1,$2,$3)
       ON CONFLICT ("tipo") DO UPDATE SET "niveles" = EXCLUDED."niveles", "imagenId" = EXCLUDED."imagenId"
       RETURNING *`,
      [tipo, JSON.stringify(niveles), imagenId || null]
    );
    res.json({ success: true, estructura: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

/* =========================================================
   MÒDUL DISSENY VISUAL DEL CASTELL (etiquetes de text sobre
   la imatge del tronc — mateix patró que la plantilla de pinya)
   ========================================================= */

// ⚠️ TEMPORAL: crea la taula del disseny visual del castell. Sense
// ?confirm=si només avisa.
app.get('/api/migrate-castell-plantilla', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({ success: false, aviso: 'Esto crea la tabla castell_plantilla_posicion. Añade ?confirm=si para confirmar.' });
  }
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS castell_plantilla_posicion (
        "id" SERIAL PRIMARY KEY,
        "tipo" TEXT NOT NULL,
        "slot" TEXT NOT NULL,
        "slotIndex" INTEGER NOT NULL DEFAULT 1,
        "x" NUMERIC NOT NULL,
        "y" NUMERIC NOT NULL,
        "w" NUMERIC NOT NULL DEFAULT 90,
        "h" NUMERIC NOT NULL DEFAULT 28,
        UNIQUE ("tipo", "slot", "slotIndex")
      )
    `);
    res.json({ success: true, aviso: 'Borra /api/migrate-castell-plantilla del server.js ahora que ya la has ejecutado.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.get('/api/castell-plantilla/:tipo', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM castell_plantilla_posicion WHERE "tipo" = $1 ORDER BY "id"', [req.params.tipo]);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

app.put('/api/castell-plantilla/:tipo', async (req, res) => {
  const { tipo } = req.params;
  const { posiciones } = req.body;
  if (!Array.isArray(posiciones)) return res.status(400).json({ error: 'posiciones ha de ser un array' });

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('DELETE FROM castell_plantilla_posicion WHERE "tipo" = $1', [tipo]);
    for (const p of posiciones) {
      await client.query(
        `INSERT INTO castell_plantilla_posicion ("tipo","slot","slotIndex","x","y","w","h")
         VALUES ($1,$2,$3,$4,$5,$6,$7)`,
        [tipo, p.slot, p.slotIndex || 1, p.x, p.y, p.w || 90, p.h || 28]
      );
    }
    await client.query('COMMIT');
    res.json({ success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`Servidor corriendo en puerto ${PORT}`);
});