const express = require('express');
const { Pool } = require('pg');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');

const app = express();

// 🛡️ Seguridad base
// - helmet añade cabeceras seguras por defecto (oculta X-Powered-By, evita
//   sniffing de tipo MIME, fija Content-Security-Policy básica, etc.)
app.disable('x-powered-by');
app.use(helmet());

// - límite de peticiones por IP: mitiga fuerza bruta / scraping masivo
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutos
  max: 300,                 // peticiones por IP en esa ventana
  standardHeaders: true,
  legacyHeaders: false
});
app.use('/api/', limiter);

app.use(express.json({ limit: '1mb' })); // límite de tamaño de body, evita payloads gigantes
app.use(express.static('public', {
  dotfiles: 'deny', // nunca sirvas .env, .git, etc.
  index: ['index.html']
}));

// Nota sobre inyección SQL: todas las consultas de este archivo usan
// parámetros ($1, $2...) de node-postgres en vez de concatenar texto, que
// es la defensa real contra SQL injection. Nunca metas variables directamente
// dentro de un template string SQL (`... WHERE x = ${valor}`), siempre $n.

// 🔑 Conexión a PostgreSQL (Render)
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

// Respuesta de error genérica: registra el detalle real en el log del
// servidor (Render lo verás en tus logs), pero nunca lo devuelve tal cual
// al cliente — un mensaje de error de Postgres puede revelar nombres de
// tabla/columna útiles para un atacante.
function errorHandler(res, error, mensajePublico = 'Error del servidor') {
  console.error(error);
  res.status(500).json({ success: false, error: mensajePublico });
}

// 🔥 TEST DB
app.get('/api/test-db', async (req, res) => {
  try {
    const result = await pool.query('SELECT NOW()');
    res.json({
      success: true,
      time: result.rows[0],
    });
  } catch (error) {
    errorHandler(res, error, 'No se pudo conectar a la base de datos');
  }
});

// ⚠️ TEMPORAL: BORRA la tabla castellers ENTERA (todas las columnas y filas)
// y la crea de nuevo con el esquema alineado 1:1 al CSV. Sin ?confirm=si
// solo muestra un aviso; con ?confirm=si sí que la borra y recrea.
// BÓRRALA del código en cuanto la hayas ejecutado una vez.
// ⚠️ TEMPORAL: BORRA por completo los datos de miembros (castellers +
// sus rols de castell asignados) y recrea la tabla con el esquema FINAL
// (con "posicionPinyaId", sin la vieja columna "rol"). Los catálogos
// roles_castillo / posiciones_pinya NO se tocan (se crean/siembran si
// faltan). Sin ?confirm=si solo avisa. BÓRRALA del código en cuanto la
// hayas ejecutado.
app.get('/api/reset-miembros', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto BORRA todos los castellers y sus rols asignados, y recrea la tabla con el esquema final. Añade ?confirm=si para confirmar, ej: /api/reset-miembros?confirm=si'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS posiciones_pinya (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `CREATE TABLE IF NOT EXISTS roles_castillo (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `INSERT INTO posiciones_pinya ("nombre") VALUES
       ('MANS'), ('NOVATOS'), ('CROSSES'), ('LATERALS'), ('CONTRAFORTS'),
       ('BAIXOS'), ('DAUS'), ('GRALLES I TABALS'), ('ALTRES')
     ON CONFLICT ("nombre") DO NOTHING`,
    `INSERT INTO roles_castillo ("nombre") VALUES
       ('Baix'), ('Segon'), ('Terç'), ('Acotxador'), ('Enxaneta')
     ON CONFLICT ("nombre") DO NOTHING`,
    `DROP TABLE IF EXISTS casteller_roles`,
    `DROP TABLE IF EXISTS castellers CASCADE`,
    `CREATE TABLE castellers (
       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       "nombre" TEXT NOT NULL,
       "primerApellido" TEXT,
       "segundoApellido" TEXT,
       "apodo" TEXT,
       "posicionPinyaId" INTEGER REFERENCES posiciones_pinya("id"),
       "accesoAPP" BOOLEAN,
       "correo" TEXT,
       "fNac" DATE,
       "movil" TEXT,
       "fechaCamisa" DATE,
       "alturaHombros" INTEGER,
       "revisado" BOOLEAN,
       "estadoAcogida" TEXT,
       "habitual" BOOLEAN,
       "permisosAPP" TEXT[],
       "integranteColla" BOOLEAN,
       "lesionLargoPlazo" BOOLEAN,
       "formularios" INTEGER,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     )`,
    `CREATE TABLE casteller_roles (
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       "rolId" INTEGER NOT NULL REFERENCES roles_castillo("id") ON DELETE CASCADE,
       "orden" INTEGER NOT NULL,
       PRIMARY KEY ("castellerId", "rolId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  const fallos = resultados.filter(r => !r.ok);
  res.json({
    success: fallos.length === 0,
    detalle: resultados,
    aviso: 'Tabla de miembros recreada. Borra /api/reset-miembros del server.js ahora que ya la has usado. Después de importar el CSV, visita una vez /api/fix-id-sequence.'
  });
});

// ⚠️ TEMPORAL: separa "rol" (texto libre, hoy la Posició del CSV) en dos
// conceptos: catálogo de posicions de pinya (FK, un valor por casteller) y
// catálogo de rols de castell (vector ordenado, varios por casteller, vía
// la taula pont casteller_roles). Migra los datos existentes de "rol" hacia
// "posicionPinyaId" antes de borrar la columna de texto. Sin ?confirm=si
// solo avisa. BÓRRALA del código en cuanto la hayas ejecutado.
app.get('/api/migrate-roles', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea roles_castillo, posiciones_pinya y casteller_roles, migra "rol" a "posicionPinyaId" y borra la columna "rol". Añade ?confirm=si para confirmar.'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS roles_castillo (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `CREATE TABLE IF NOT EXISTS posiciones_pinya (
       "id" SERIAL PRIMARY KEY,
       "nombre" TEXT UNIQUE NOT NULL
     )`,
    `INSERT INTO roles_castillo ("nombre") VALUES
       ('Baix'), ('Segon'), ('Terç'), ('Acotxador'), ('Enxaneta')
     ON CONFLICT ("nombre") DO NOTHING`,
    `INSERT INTO posiciones_pinya ("nombre") VALUES
       ('MANS'), ('NOVATOS'), ('CROSSES'), ('LATERALS'), ('CONTRAFORTS'),
       ('BAIXOS'), ('DAUS'), ('GRALLES I TABALS'), ('ALTRES')
     ON CONFLICT ("nombre") DO NOTHING`,
    `ALTER TABLE castellers ADD COLUMN IF NOT EXISTS "posicionPinyaId" INTEGER REFERENCES posiciones_pinya("id")`,
    `UPDATE castellers c
       SET "posicionPinyaId" = pp."id"
       FROM posiciones_pinya pp
       WHERE pp."nombre" = c."rol" AND c."posicionPinyaId" IS NULL`,
    `ALTER TABLE castellers DROP COLUMN IF EXISTS "rol"`,
    `CREATE TABLE IF NOT EXISTS casteller_roles (
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       "rolId" INTEGER NOT NULL REFERENCES roles_castillo("id") ON DELETE CASCADE,
       "orden" INTEGER NOT NULL,
       PRIMARY KEY ("castellerId", "rolId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  const fallos = resultados.filter(r => !r.ok);
  res.json({
    success: fallos.length === 0,
    detalle: resultados,
    aviso: 'Borra /api/migrate-roles del server.js ahora que ya la has ejecutado.'
  });
});

// ⚠️ TEMPORAL: tras importar el CSV (que trae sus propios "id" con huecos,
// del 1 al 1434), la secuencia interna de autoincremento de Postgres no se
// entera de esos valores. Esto la deja apuntando al siguiente número libre,
// para que añadir un casteller nuevo a mano no choque con un id importado.
// BÓRRALA también del código cuando ya no la necesites.
app.get('/api/fix-id-sequence', async (req, res) => {
  try {
    await pool.query(
      `SELECT setval(pg_get_serial_sequence('castellers', 'id'), COALESCE((SELECT MAX("id") FROM castellers), 1))`
    );
    res.json({ success: true, mensaje: 'Seqüència d\'id ajustada correctament.' });
  } catch (error) {
    errorHandler(res, error);
  }
});

// api para cargar miembros y sus datos
app.post('/api/castellers', async (req, res) => {
  try {
    const {
      id, nombre, primerApellido, segundoApellido, apodo, posicionPinyaId,
      accesoAPP, correo, fNac, movil, fechaCamisa, alturaHombros,
      revisado, estadoAcogida, habitual, permisosAPP, integranteColla,
      lesionLargoPlazo, formularios
    } = req.body;

    if (!nombre) {
      return res.status(400).json({ error: 'nombre es obligatorio' });
    }

    const columnas = [
      'nombre', 'primerApellido', 'segundoApellido', 'apodo', 'posicionPinyaId',
      'accesoAPP', 'correo', 'fNac', 'movil', 'fechaCamisa', 'alturaHombros',
      'revisado', 'estadoAcogida', 'habitual', 'permisosAPP', 'integranteColla',
      'lesionLargoPlazo', 'formularios'
    ];
    const valores = [
      nombre,
      primerApellido || null,
      segundoApellido || null,
      apodo || null,
      (posicionPinyaId === '' || posicionPinyaId === undefined) ? null : posicionPinyaId,
      accesoAPP === undefined ? null : accesoAPP,
      correo || null,
      fNac || null,
      movil || null,
      fechaCamisa || null,
      (alturaHombros === '' || alturaHombros === undefined) ? null : alturaHombros,
      revisado === undefined ? null : revisado,
      estadoAcogida || null,
      habitual === undefined ? null : habitual,
      Array.isArray(permisosAPP) ? permisosAPP : (permisosAPP ? [permisosAPP] : null),
      integranteColla === undefined ? null : integranteColla,
      lesionLargoPlazo === undefined ? null : lesionLargoPlazo,
      (formularios === '' || formularios === undefined) ? null : formularios
    ];

    // Si viene un "id" explícito (p. ej. al importar el CSV), lo respetamos.
    // Si no, dejamos que la tabla lo autogenere (alta manual de un casteller).
    if (id !== undefined && id !== null && id !== '') {
      columnas.unshift('id');
      valores.unshift(id);
    }

    const columnasSQL = columnas.map(c => `"${c}"`).join(', ');
    const placeholders = columnas.map((_, i) => `$${i + 1}`).join(', ');

    const result = await pool.query(
      `INSERT INTO castellers (${columnasSQL}) VALUES (${placeholders}) RETURNING *`,
      valores
    );

    res.json({
      success: true,
      casteller: result.rows[0]
    });

  } catch (error) {
    errorHandler(res, error);
  }
});

//api para visualizar miembros (incluye posició pinya i el vector de rols de castell)
app.get('/api/castellers', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT
        c.*,
        pp."nombre" AS "posicionPinyaNombre",
        COALESCE(
          (SELECT json_agg(json_build_object('id', rc."rolId", 'nombre', rcast."nombre", 'orden', rc."orden") ORDER BY rc."orden")
           FROM casteller_roles rc
           JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
           WHERE rc."castellerId" = c."id"),
          '[]'
        ) AS "rolesCastell"
      FROM castellers c
      LEFT JOIN posiciones_pinya pp ON pp."id" = c."posicionPinyaId"
      ORDER BY c."id" DESC
    `);
    res.json({
      success: true,
      data: result.rows
    });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api para el catàleg de posicions de pinya
app.get('/api/posiciones-pinya', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM posiciones_pinya ORDER BY "id"');
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api para el catàleg de rols de castell
app.get('/api/roles-castillo', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM roles_castillo ORDER BY "id"');
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api per llegir el vector de rols (ordenat) d'un casteller concret
app.get('/api/castellers/:id/roles', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `SELECT rc."rolId" AS "id", rcast."nombre", rc."orden"
       FROM casteller_roles rc
       JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
       WHERE rc."castellerId" = $1
       ORDER BY rc."orden"`,
      [id]
    );
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

//api per desar el vector de rols (ordenat, el primer és el principal) d'un casteller
app.put('/api/castellers/:id/roles', async (req, res) => {
  const { id } = req.params;
  const { rolIds } = req.body; // array ordenat d'ids de roles_castillo

  if (!Array.isArray(rolIds)) {
    return res.status(400).json({ error: 'rolIds ha de ser un array d\'ids, en ordre (principal primer)' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('DELETE FROM casteller_roles WHERE "castellerId" = $1', [id]);

    for (let i = 0; i < rolIds.length; i++) {
      await client.query(
        `INSERT INTO casteller_roles ("castellerId", "rolId", "orden") VALUES ($1, $2, $3)`,
        [id, rolIds[i], i + 1]
      );
    }

    await client.query('COMMIT');
    res.json({ success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    errorHandler(res, error);
  } finally {
    client.release();
  }
});

//api para editar un miembro existente
app.put('/api/castellers/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const {
      nombre, primerApellido, segundoApellido, apodo, posicionPinyaId,
      accesoAPP, correo, fNac, movil, fechaCamisa, alturaHombros,
      revisado, estadoAcogida, habitual, permisosAPP, integranteColla,
      lesionLargoPlazo, formularios
    } = req.body;

    if (!nombre) {
      return res.status(400).json({ error: 'nombre es obligatorio' });
    }

    const result = await pool.query(
      `UPDATE castellers SET
         "nombre" = $1, "primerApellido" = $2, "segundoApellido" = $3, "apodo" = $4, "posicionPinyaId" = $5,
         "accesoAPP" = $6, "correo" = $7, "fNac" = $8, "movil" = $9, "fechaCamisa" = $10,
         "alturaHombros" = $11, "revisado" = $12, "estadoAcogida" = $13, "habitual" = $14,
         "permisosAPP" = $15, "integranteColla" = $16, "lesionLargoPlazo" = $17, "formularios" = $18
       WHERE "id" = $19
       RETURNING *`,
      [
        nombre,
        primerApellido || null,
        segundoApellido || null,
        apodo || null,
        (posicionPinyaId === '' || posicionPinyaId === undefined) ? null : posicionPinyaId,
        accesoAPP === undefined ? null : accesoAPP,
        correo || null,
        fNac || null,
        movil || null,
        fechaCamisa || null,
        (alturaHombros === '' || alturaHombros === undefined) ? null : alturaHombros,
        revisado === undefined ? null : revisado,
        estadoAcogida || null,
        habitual === undefined ? null : habitual,
        Array.isArray(permisosAPP) ? permisosAPP : (permisosAPP ? [permisosAPP] : null),
        integranteColla === undefined ? null : integranteColla,
        lesionLargoPlazo === undefined ? null : lesionLargoPlazo,
        (formularios === '' || formularios === undefined) ? null : formularios,
        id
      ]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Casteller no trobat' });
    }

    res.json({
      success: true,
      casteller: result.rows[0]
    });

  } catch (error) {
    errorHandler(res, error);
  }
});

//api generar castells
// Cada casteller ahora puede tener VARIOS rols de castell asignados
// (baix/segon/terç/acotxador/enxaneta), guardados en casteller_roles con un
// orden (1 = principal). Para generar propuestas, contamos a alguien como
// elegible para un rol si ese rol está en su vector, sin importar el orden
// — es una asunción de partida (cualquier rol asignado cuenta igual), no
// distingue todavía "rol principal" de "también sabe hacerlo".
app.get('/api/generar', async (req, res) => {
  try {
    const resultado = await pool.query(`
      SELECT
        c."id", c."nombre", c."alturaHombros",
        COALESCE(
          array_agg(lower(rcast."nombre")) FILTER (WHERE rcast."nombre" IS NOT NULL),
          '{}'
        ) AS roles
      FROM castellers c
      LEFT JOIN casteller_roles rc ON rc."castellerId" = c."id"
      LEFT JOIN roles_castillo rcast ON rcast."id" = rc."rolId"
      GROUP BY c."id"
    `);
    const castellers = resultado.rows;

    const obtenerMasAltos = (arr) => [...arr].sort((a, b) => b.alturaHombros - a.alturaHombros);
    const obtenerMasBajos = (arr) => [...arr].sort((a, b) => a.alturaHombros - b.alturaHombros);

    const estructuras = [
      { nombre: '2d6', segons: 2, tersos: 2 },
      { nombre: '3d7', segons: 3, tersos: 3 },
      { nombre: '4d7', segons: 4, tersos: 4 },
      { nombre: '5d7', segons: 5, tersos: 5 }
    ];

    const calcularRiesgo = ({ baix, segons, tersos, pom }) => {
      let riesgo = 0;

      const mediaSegons = segons.reduce((acc, s) => acc + s.alturaHombros, 0) / segons.length;
      const mediaTersos = tersos.reduce((acc, t) => acc + t.alturaHombros, 0) / tersos.length;

      riesgo += Math.abs(baix.alturaHombros - mediaSegons) * 0.3;
      riesgo += Math.abs(mediaSegons - mediaTersos) * 0.3;

      if (pom.enxaneta.alturaHombros > 140) riesgo += 20;
      if (pom.acotxador.alturaHombros > 150) riesgo += 15;

      return Math.round(riesgo);
    };

    const clasificarRiesgo = (riesgo) => {
      if (riesgo < 20) return '🟢 Seguro';
      if (riesgo < 50) return '🟡 Medio';
      return '🔴 Alto';
    };

    const generarParaEstructura = (config) => {

      const baixos = castellers.filter(c => c.roles.includes('baix'));
      const segons = castellers.filter(c => c.roles.includes('segon'));
      const tersos = castellers.filter(c => c.roles.includes('terç'));
      const acotxadors = castellers.filter(c => c.roles.includes('acotxador'));
      const enxanetes = castellers.filter(c => c.roles.includes('enxaneta'));

      const resultado = {
        tipo: config.nombre,
        valido: true,
        mensajes: []
      };

      if (baixos.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta baix');
      }

      if (segons.length < config.segons) {
        resultado.valido = false;
        resultado.mensajes.push(`Faltan segons (${config.segons})`);
      }

      if (tersos.length < config.tersos) {
        resultado.valido = false;
        resultado.mensajes.push(`Faltan tersos (${config.tersos})`);
      }

      if (acotxadors.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta acotxador');
      }

      if (enxanetes.length < 1) {
        resultado.valido = false;
        resultado.mensajes.push('Falta enxaneta');
      }

      if (!resultado.valido) return resultado;

      const estructura = {
        baix: obtenerMasAltos(baixos)[0],
        segons: obtenerMasAltos(segons).slice(0, config.segons),
        tersos: obtenerMasAltos(tersos).slice(0, config.tersos),
        pom: {
          acotxador: obtenerMasBajos(acotxadors)[0],
          enxaneta: obtenerMasBajos(enxanetes)[0]
        }
      };

      const riesgo = calcularRiesgo(estructura);
      const nivel = clasificarRiesgo(riesgo);

      resultado.estructura = estructura;
      resultado.riesgo = riesgo;
      resultado.nivel = nivel;

      return resultado;
    };

    const propuestas = estructuras.map(config => generarParaEstructura(config));

    res.json({
      success: true,
      propuestas
    });

  } catch (error) {
    console.error(error);
    res.status(500).send('Error generando castells');
  }
});

/* =========================================================
   MÒDUL ENSAJOS
   ========================================================= */

// ⚠️ TEMPORAL: crea les taules d'ensayos i assistència. Sense ?confirm=si
// només avisa. BÓRRALA del server.js en cuanto la hayas ejecutado.
app.get('/api/migrate-ensayos', async (req, res) => {
  if (req.query.confirm !== 'si') {
    return res.json({
      success: false,
      aviso: 'Esto crea las tablas ensayos y ensayo_asistentes. Añade ?confirm=si para confirmar.'
    });
  }

  const statements = [
    `CREATE TABLE IF NOT EXISTS ensayos (
       "id" SERIAL PRIMARY KEY,
       "fecha" DATE NOT NULL,
       "horaInicio" TIME,
       "horaFin" TIME,
       "notas" TEXT,
       "publicado" BOOLEAN NOT NULL DEFAULT FALSE,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     )`,
    `CREATE TABLE IF NOT EXISTS ensayo_asistentes (
       "ensayoId" INTEGER NOT NULL REFERENCES ensayos("id") ON DELETE CASCADE,
       "castellerId" INTEGER NOT NULL REFERENCES castellers("id") ON DELETE CASCADE,
       PRIMARY KEY ("ensayoId", "castellerId")
     )`
  ];

  const resultados = [];
  for (const sql of statements) {
    try {
      await pool.query(sql);
      resultados.push({ sql, ok: true });
    } catch (err) {
      resultados.push({ sql, ok: false, error: err.message });
    }
  }

  res.json({
    success: resultados.every(r => r.ok),
    detalle: resultados,
    aviso: 'Borra /api/migrate-ensayos del server.js ahora que ya la has ejecutado.'
  });
});

// Llistar tots els ensayos (esborranys inclosos — encara no hi ha usuaris
// per restringir la visibilitat dels privats; això arribarà amb el login)
app.get('/api/ensayos', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT e.*, COUNT(ea."castellerId")::int AS "numAsistentes"
      FROM ensayos e
      LEFT JOIN ensayo_asistentes ea ON ea."ensayoId" = e."id"
      GROUP BY e."id"
      ORDER BY e."fecha" DESC, e."id" DESC
    `);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Crear un ensayo nou
app.post('/api/ensayos', async (req, res) => {
  try {
    const { fecha, horaInicio, horaFin, notas } = req.body;
    if (!fecha) return res.status(400).json({ error: 'fecha es obligatoria' });

    const result = await pool.query(
      `INSERT INTO ensayos ("fecha", "horaInicio", "horaFin", "notas")
       VALUES ($1, $2, $3, $4) RETURNING *`,
      [fecha, horaInicio || null, horaFin || null, notas || null]
    );
    res.json({ success: true, ensayo: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Detall d'un ensayo + llista d'ids de castellers presents
app.get('/api/ensayos/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const ensayo = await pool.query('SELECT * FROM ensayos WHERE "id" = $1', [id]);
    if (ensayo.rows.length === 0) return res.status(404).json({ error: 'Ensayo no trobat' });

    const asistentes = await pool.query(
      'SELECT "castellerId" FROM ensayo_asistentes WHERE "ensayoId" = $1',
      [id]
    );
    res.json({
      success: true,
      ensayo: ensayo.rows[0],
      asistentesIds: asistentes.rows.map(r => r.castellerId)
    });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Marcar/desmarcar l'assistència d'un casteller a un ensayo
app.put('/api/ensayos/:id/asistencia', async (req, res) => {
  try {
    const { id } = req.params;
    const { castellerId, asiste } = req.body;
    if (!castellerId) return res.status(400).json({ error: 'castellerId es obligatorio' });

    if (asiste) {
      await pool.query(
        `INSERT INTO ensayo_asistentes ("ensayoId", "castellerId") VALUES ($1, $2)
         ON CONFLICT DO NOTHING`,
        [id, castellerId]
      );
    } else {
      await pool.query(
        `DELETE FROM ensayo_asistentes WHERE "ensayoId" = $1 AND "castellerId" = $2`,
        [id, castellerId]
      );
    }
    res.json({ success: true });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Publicar un ensayo (deixa de ser esborrany privat)
app.put('/api/ensayos/:id/publicar', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `UPDATE ensayos SET "publicado" = TRUE WHERE "id" = $1 RETURNING *`,
      [id]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Ensayo no trobat' });
    res.json({ success: true, ensayo: result.rows[0] });
  } catch (error) {
    errorHandler(res, error);
  }
});

// Propostes de castells PER A UN ENSAYO CONCRET, basades només en els
// presents (encara no tenim rols de castell assignats de forma fiable a
// totes les collas que faran servir això, així que aquí NO exigim rols:
// només comptem caps i, opcionalment, ordenem per alçada).
// ?criterio=altura -> suggereix qui podria anar de pom (més baixos) i de
// base (més alts). ?criterio=ninguno (o sense el paràmetre) -> només
// comprova viabilitat per nombre de gent.
app.get('/api/ensayos/:id/propuestas', async (req, res) => {
  try {
    const { id } = req.params;
    const criterio = req.query.criterio === 'altura' ? 'altura' : 'ninguno';

    const result = await pool.query(
      `SELECT c."id", c."nombre", c."alturaHombros"
       FROM ensayo_asistentes ea
       JOIN castellers c ON c."id" = ea."castellerId"
       WHERE ea."ensayoId" = $1`,
      [id]
    );
    const presentes = result.rows;

    // Estructures simplificades: nombre mínim de persones al tronc + pom
    // (1 baix + segons + tersos + acotxador + enxaneta). No modelem encara
    // la pinya de suport.
    const estructuras = [
      { tipo: '2d6', segons: 2, tersos: 2 },
      { tipo: '3d7', segons: 3, tersos: 3 },
      { tipo: '4d7', segons: 4, tersos: 4 },
      { tipo: '5d7', segons: 5, tersos: 5 }
    ];

    const propuestas = estructuras.map(e => {
      const requerido = 1 + e.segons + e.tersos + 1 + 1; // baix + segons + tersos + acotxador + enxaneta
      const viable = presentes.length >= requerido;

      const propuesta = { tipo: e.tipo, requerido, presentes: presentes.length, viable };

      if (viable && criterio === 'altura') {
        const conAltura = presentes.filter(p => p.alturaHombros !== null && p.alturaHombros !== undefined);
        const ordenados = [...conAltura].sort((a, b) => a.alturaHombros - b.alturaHombros);
        propuesta.sugerencia = {
          pom_mas_bajos: ordenados.slice(0, 2).map(p => ({ id: p.id, nombre: p.nombre, alturaHombros: p.alturaHombros })),
          base_mas_altos: ordenados.slice(-2).reverse().map(p => ({ id: p.id, nombre: p.nombre, alturaHombros: p.alturaHombros })),
          sinAlturaRegistrada: presentes.length - conAltura.length
        };
      }

      return propuesta;
    });

    res.json({ success: true, criterio, propuestas });
  } catch (error) {
    errorHandler(res, error);
  }
});


const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`Servidor corriendo en puerto ${PORT}`);
});